server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
            - id: course-service
              uri: http://localhost:8082
              predicates:
                - Path=/courses/**
            - id: enrollment-service
              uri: http://localhost:8083
              predicates:
                - Path=/enrollment/**
