server:
  port: 8080

spring:
  application:
    name: gateway-service

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:9081
              predicates:
                - Path=/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authCB
                    fallbackUri: forward:/fallback/auth
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1   # ~1/60 requests per second
                    redis-rate-limiter.burstCapacity: 1
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

            - id: course-service
              uri: http://localhost:8082
              predicates:
                - Path=/courses/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: courseCB
                    fallbackUri: forward:/fallback/course
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

            - id: enrollment-service
              uri: http://localhost:8083
              predicates:
                - Path=/enrollment/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: enrollmentCB
                    fallbackUri: forward:/fallback/enrollment
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
